name: mo-bvt-test
description: "Start MatrixOne Service BVT Test"
inputs:
  host:
    description: 'host used by mysql to connection'
    required: true
    default: ""
  cn_ips:
    description: "matrixone cns' ip"
    required: true
    default: ""
  repo:
    description: 'matrixone repository'
    required: true
    default: "matrixorigin/matrixone"
  ref:
    description: 'matrixone repository branch(or commit)'
    required: true
    default: "main"
  username:
    description: 'username for connect to matrixone'
    required: true
    default: "dump"
  password:
    description: 'password for connect to matrixone'
    required: true
    default: "111"
  resource-path:
    description: 'the resource path required by bvt to load'
    required: true
    default: "/matrixone/test/distributed/resources"
  exclude-cases:
    description: 'bvt exclude cases'
    required: true
    default: "optimistic"
  upload-file-name:
    description: 'upload report file name'
    required: true
    default: "mo-regression-bvt"

runs:
  using: "composite"
  steps:
    - name: Clone Repo ${{ inputs.repo }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        fetch-depth: 1
        path: ./matrixone
    - name: Clone Repo MO-Tester
      uses: actions/checkout@v4
      with:
        repository: matrixorigin/mo-tester
        path: ./mo-tester
        ref: main
    - name: Set JAVA PATH
      shell: /bin/bash
      run: |
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH
    - name: Modify MO-Tester Config
      if: ${{ always() && !cancelled() }}
      shell: /bin/bash
      run: |
        sed -i "s/127.0.0.1:6001/${{ inputs.host }}:6001/" ./mo-tester/mo.yml
        sed -i 's/socketTimeout:.*/socketTimeout: 300000/g' ./mo-tester/mo.yml
        sed -i 's/  serverIP: "127.0.0.1"/  serverIP: "${{ inputs.cn_ips }}"/g' ./mo-tester/mo.yml
        sed -i 's/waittime:.*/waittime: 2000/g' ./mo-tester/run.yml
        cat ./mo-tester/mo.yml
        echo "=========================="
        cat ./mo-tester/run.yml

    - name: Start BVT Test
      shell: /bin/bash
      timeout-minutes: 40
      run: |
        export LC_ALL="C.UTF-8"
        locale
        echo "=========================="

        cd $GITHUB_WORKSPACE/mo-tester
        ./run.sh -n -g -o -p $GITHUB_WORKSPACE/matrixone/test/distributed/cases -s ${{ inputs.resource-path }} -e ${{ inputs.exclude-cases }}  2>&1
        rm -rf .git lib
    - name: Collect Upload files
      shell: /bin/bash
      if: ${{ always() }}
      run: |
        mkdir -p $GITHUB_WORKSPACE/reports/mo-tester
        mkdir -p $GITHUB_WORKSPACE/mo-tester && cp -r $GITHUB_WORKSPACE/mo-tester $GITHUB_WORKSPACE/reports/mo-tester
    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      continue-on-error: true
      with:
        name: mo-regression-bvt
        path: |
            ${{ github.workspace }}/reports